plugins {
    id 'java'
}

group = 'io.jieun'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    // https://mvnrepository.com/artifact/com.h2database/h2
    runtimeOnly 'com.h2database:h2:2.3.232'

    // https://mvnrepository.com/artifact/ch.qos.logback/logback-classic
    implementation 'ch.qos.logback:logback-classic:1.5.18'

    compileOnly "org.projectlombok:lombok:1.18.38"
    annotationProcessor "org.projectlombok:lombok:1.18.38"

    testCompileOnly "org.projectlombok:lombok:1.18.38"
    testAnnotationProcessor "org.projectlombok:lombok:1.18.38"


    // https://mvnrepository.com/artifact/org.hibernate.orm/hibernate-core
    implementation 'org.hibernate.orm:hibernate-core:7.0.0.Beta2'

    // https://mvnrepository.com/artifact/com.mysql/mysql-connector-j
    implementation 'com.mysql:mysql-connector-j:9.2.0'

    // https://mvnrepository.com/artifact/org.assertj/assertj-core
    testImplementation 'org.assertj:assertj-core:3.27.3'

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}